### ISSUE TITLE
pihole service not available at tailscale url port 53

### ISSUE THREAD

**Issue by tyler-stefani** [2Tiny2Scale/ScaleTail#84]
Hello!

I am running into an issue where the pihole service isn't available from port 53 though the tailscale url. Upon running `docker compose up` and starting the two containers successfully, I am able to do the following:
- Access `<local-ip>:80/admin` and `<local-ip>:53` when I expose to container ports to the host
- Access `<tailscale-ip>:80/admin` and log in using the configured web password

I am not able to use the pihole service through `<tailscale-ip>:53` with this config. Using `telnet <tailscale-ip> 53` results in a disconnect, meaning the 53 port is not available.

I also attempted to use nsenter with netstat into both containers and got the following response:
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 172.20.0.2:40166        <...>.compute.amazonaws.com:https ESTABLISHED
tcp        0      0 172.20.0.2:39668        derp12f.tailscale.com:https ESTABLISHED
tcp        0      0 localhost:40782         localhost:41234         TIME_WAIT
tcp        0      0 localhost:trinity-dist  localhost:58890         TIME_WAIT
tcp        0      0 172.20.0.2:57776        <...>.compute-1.amazonaws.com:https ESTABLISHED
```
and more of the same running netstat on my host
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 homeserver:53648        <...>.compute-1.amazonaws.com:https ESTABLISHED
tcp        0      0 homeserver:42734        derp12f.tailscale.com:https ESTABLISHED
tcp        0      0 homeserver:59426       <...>.compute.amazonaws.com:https ESTABLISHED
udp        0      0 homeserver:bootpc       _gateway:bootps         ESTABLISHED
```
It appears that nothing listening on port 53 (or 80), so I think the DNSStubListener is neither enabled nor getting in the way.

For reference, here is the slightly tweaked docker-compose.yml that I'm using:
```yaml
services:
  # Make sure you have updated/checked the .env file with the correct variables.
   # All the ${ xx } need to be defined there.
   # Tailscale Sidecar Configuration
   tailscale:
      image: tailscale/tailscale:latest # Image to be used
      container_name: tailscale-${SERVICE} # Name for local container management
      hostname: ${SERVICE} # Name used within your Tailscale environment
      environment:
        - TS_AUTHKEY=${TS_AUTHKEY}
        - TS_STATE_DIR=/var/lib/tailscale
     # - TS_SERVE_CONFIG=/config/serve.json # Tailsacale Serve configuration to expose the web interface on your local Tailnet - remove this line if not required
        - TS_USERSPACE=false
        - TS_ENABLE_HEALTH_CHECK=true              # Enable healthcheck endpoint: "/healthz"
        - TS_LOCAL_ADDR_PORT=127.0.0.1:41234       # The <addr>:<port> for the healthz endpoint
        - TS_EXTRA_ARGS=--advertise-tags=tag:container --accept-dns=true # Uncomment when using MagicDNS
    volumes:
       - ${PWD}/config:/config # Config folder used to store Tailscale files - you may need to change the path
       - ${PWD}/ts/state:/var/lib/tailscale # Tailscale requirement - you may need to change the path
    devices:
       - /dev/net/tun:/dev/net/tun # Network configuration for Tailscale to work
    ap_add:
       - net_admin # Tailscale requirement
       - sys_module # Tailscale requirement
    #ports:
    #  - 0.0.0.0:${SERVICEPORT}:${SERVICEPORT} # Binding port ${SERVICE}PORT to the local network - may be removed if only exposure to your Tailnet is required
    # If any DNS issues arise, use your preferred DNS provider by uncommenting the config below
    dns:
      - ${DNS_SERVER}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:41234/healthz"] # Check Tailscale has a Tailnet IP and is operational
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 10s # Time to wait before starting health checks
   restart: always

# ${SERVICE}
 application:
   image: ${IMAGE_URL} # Image to be used
   network_mode: service:tailscale # Sidecar configuration to route ${SERVICE} through Tailscale
   container_name: app-${SERVICE} # Name for local container management
   environment:
     - PUID=1000
     - PGID=1000
     - TZ=America/Chicago
     - WEBPASSWORD=${WEBPASSWORD}
   volumes:
    - ${PWD}/${SERVICE}-data/etc-pihole:/etc/pihole
    - ${PWD}/${SERVICE}-data/etc-dnsmasq.d:/etc/dnsmasq.d
  #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
   depends_on:
     tailscale:
       condition: service_healthy
   healthcheck:
     test: ["CMD", "pgrep", "-f", "pihole-FTL"] # Check if ${SERVICE} process is running
     interval: 1m # How often to perform the check
     timeout: 10s # Time to wait for the check to succeed
     retries: 3 # Number of retries before marking as unhealthy
     start_period: 30s # Time to wait before starting health checks
   restart: always
```

Any ideas as to what I might be missing? Or if this is a bug? I can create a pull request for any necessary fixes.

Thank you!
